FROM golang:alpine

COPY . /project

WORKDIR /project

RUN go build -o build/go_sub_service ./application/microservices/subscription/cmd/
RUN ls | grep -v 'go' | grep -v 'Docker' | grep -v 'Readme' | grep -v 'build' xargs rm -rfv
RUN ls | grep -v 'build' | xargs rm

CMD ["/project/build/go_sub_service"]