// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: kudago.proto

package kudago_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num  uint64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kudago_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_kudago_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_kudago_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Input) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kudago_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_kudago_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_kudago_proto_rawDescGZIP(), []int{1}
}

var File_kudago_proto protoreflect.FileDescriptor

var file_kudago_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6b, 0x75, 0x64, 0x61, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d,
	0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x44, 0x0a, 0x06, 0x4b, 0x75, 0x64, 0x61, 0x67, 0x6f,
	0x12, 0x1c, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x42, 0x61, 0x73, 0x69, 0x63, 0x12, 0x06, 0x2e, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x1c,
	0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2e, 0x2f, 0x6b, 0x75, 0x64, 0x61, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kudago_proto_rawDescOnce sync.Once
	file_kudago_proto_rawDescData = file_kudago_proto_rawDesc
)

func file_kudago_proto_rawDescGZIP() []byte {
	file_kudago_proto_rawDescOnce.Do(func() {
		file_kudago_proto_rawDescData = protoimpl.X.CompressGZIP(file_kudago_proto_rawDescData)
	})
	return file_kudago_proto_rawDescData
}

var file_kudago_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kudago_proto_goTypes = []interface{}{
	(*Input)(nil), // 0: Input
	(*Empty)(nil), // 1: Empty
}
var file_kudago_proto_depIdxs = []int32{
	0, // 0: Kudago.AddBasic:input_type -> Input
	1, // 1: Kudago.AddToday:input_type -> Empty
	1, // 2: Kudago.AddBasic:output_type -> Empty
	1, // 3: Kudago.AddToday:output_type -> Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kudago_proto_init() }
func file_kudago_proto_init() {
	if File_kudago_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kudago_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kudago_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kudago_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kudago_proto_goTypes,
		DependencyIndexes: file_kudago_proto_depIdxs,
		MessageInfos:      file_kudago_proto_msgTypes,
	}.Build()
	File_kudago_proto = out.File
	file_kudago_proto_rawDesc = nil
	file_kudago_proto_goTypes = nil
	file_kudago_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KudagoClient is the client API for Kudago service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KudagoClient interface {
	AddBasic(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Empty, error)
	AddToday(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type kudagoClient struct {
	cc grpc.ClientConnInterface
}

func NewKudagoClient(cc grpc.ClientConnInterface) KudagoClient {
	return &kudagoClient{cc}
}

func (c *kudagoClient) AddBasic(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Kudago/AddBasic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kudagoClient) AddToday(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Kudago/AddToday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KudagoServer is the server API for Kudago service.
type KudagoServer interface {
	AddBasic(context.Context, *Input) (*Empty, error)
	AddToday(context.Context, *Empty) (*Empty, error)
}

// UnimplementedKudagoServer can be embedded to have forward compatible implementations.
type UnimplementedKudagoServer struct {
}

func (*UnimplementedKudagoServer) AddBasic(context.Context, *Input) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBasic not implemented")
}
func (*UnimplementedKudagoServer) AddToday(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToday not implemented")
}

func RegisterKudagoServer(s *grpc.Server, srv KudagoServer) {
	s.RegisterService(&_Kudago_serviceDesc, srv)
}

func _Kudago_AddBasic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KudagoServer).AddBasic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kudago/AddBasic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KudagoServer).AddBasic(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kudago_AddToday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KudagoServer).AddToday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kudago/AddToday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KudagoServer).AddToday(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kudago_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Kudago",
	HandlerType: (*KudagoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBasic",
			Handler:    _Kudago_AddBasic_Handler,
		},
		{
			MethodName: "AddToday",
			Handler:    _Kudago_AddToday_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kudago.proto",
}
