// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository.go

// Package mock_subscription is a generated GoMock package.
package mock_subscription

import (
	models "kudago/application/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountUserFollowers mocks base method.
func (m *MockRepository) CountUserFollowers(id uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserFollowers", id)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserFollowers indicates an expected call of CountUserFollowers.
func (mr *MockRepositoryMockRecorder) CountUserFollowers(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserFollowers", reflect.TypeOf((*MockRepository)(nil).CountUserFollowers), id)
}

// GetEventFollowers mocks base method.
func (m *MockRepository) GetEventFollowers(eventId uint64) (models.UsersOnEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventFollowers", eventId)
	ret0, _ := ret[0].(models.UsersOnEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventFollowers indicates an expected call of GetEventFollowers.
func (mr *MockRepositoryMockRecorder) GetEventFollowers(eventId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventFollowers", reflect.TypeOf((*MockRepository)(nil).GetEventFollowers), eventId)
}

// GetFollowers mocks base method.
func (m *MockRepository) GetFollowers(id uint64, page int) ([]models.UserCardSQL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowers", id, page)
	ret0, _ := ret[0].([]models.UserCardSQL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowers indicates an expected call of GetFollowers.
func (mr *MockRepositoryMockRecorder) GetFollowers(id, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowers", reflect.TypeOf((*MockRepository)(nil).GetFollowers), id, page)
}

// GetPlanningEvents mocks base method.
func (m *MockRepository) GetPlanningEvents(id uint64, page int) ([]models.EventCardWithDateSQL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanningEvents", id, page)
	ret0, _ := ret[0].([]models.EventCardWithDateSQL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanningEvents indicates an expected call of GetPlanningEvents.
func (mr *MockRepositoryMockRecorder) GetPlanningEvents(id, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanningEvents", reflect.TypeOf((*MockRepository)(nil).GetPlanningEvents), id, page)
}

// GetSubscriptions mocks base method.
func (m *MockRepository) GetSubscriptions(id uint64, page int) ([]models.UserCardSQL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptions", id, page)
	ret0, _ := ret[0].([]models.UserCardSQL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptions indicates an expected call of GetSubscriptions.
func (mr *MockRepositoryMockRecorder) GetSubscriptions(id, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptions", reflect.TypeOf((*MockRepository)(nil).GetSubscriptions), id, page)
}

// GetVisitedEvents mocks base method.
func (m *MockRepository) GetVisitedEvents(id uint64, page int) ([]models.EventCardWithDateSQL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVisitedEvents", id, page)
	ret0, _ := ret[0].([]models.EventCardWithDateSQL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVisitedEvents indicates an expected call of GetVisitedEvents.
func (mr *MockRepositoryMockRecorder) GetVisitedEvents(id, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVisitedEvents", reflect.TypeOf((*MockRepository)(nil).GetVisitedEvents), id, page)
}

// IsAddedEvent mocks base method.
func (m *MockRepository) IsAddedEvent(userId, eventId uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAddedEvent", userId, eventId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAddedEvent indicates an expected call of IsAddedEvent.
func (mr *MockRepositoryMockRecorder) IsAddedEvent(userId, eventId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAddedEvent", reflect.TypeOf((*MockRepository)(nil).IsAddedEvent), userId, eventId)
}

// UpdateEventStatus mocks base method.
func (m *MockRepository) UpdateEventStatus(userId, eventId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEventStatus", userId, eventId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEventStatus indicates an expected call of UpdateEventStatus.
func (mr *MockRepositoryMockRecorder) UpdateEventStatus(userId, eventId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEventStatus", reflect.TypeOf((*MockRepository)(nil).UpdateEventStatus), userId, eventId)
}
