// Code generated by MockGen. DO NOT EDIT.
// Source: ../session_manager.go

// Package mock_infrastructure is a generated GoMock package.
package mock_infrastructure

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSessionTarantool is a mock of SessionTarantool interface.
type MockSessionTarantool struct {
	ctrl     *gomock.Controller
	recorder *MockSessionTarantoolMockRecorder
}

// MockSessionTarantoolMockRecorder is the mock recorder for MockSessionTarantool.
type MockSessionTarantoolMockRecorder struct {
	mock *MockSessionTarantool
}

// NewMockSessionTarantool creates a new mock instance.
func NewMockSessionTarantool(ctrl *gomock.Controller) *MockSessionTarantool {
	mock := &MockSessionTarantool{ctrl: ctrl}
	mock.recorder = &MockSessionTarantoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionTarantool) EXPECT() *MockSessionTarantoolMockRecorder {
	return m.recorder
}

// CheckSession mocks base method.
func (m *MockSessionTarantool) CheckSession(value string) (bool, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSession", value)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckSession indicates an expected call of CheckSession.
func (mr *MockSessionTarantoolMockRecorder) CheckSession(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSession", reflect.TypeOf((*MockSessionTarantool)(nil).CheckSession), value)
}

// DeleteSession mocks base method.
func (m *MockSessionTarantool) DeleteSession(value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", value)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionTarantoolMockRecorder) DeleteSession(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionTarantool)(nil).DeleteSession), value)
}

// InsertSession mocks base method.
func (m *MockSessionTarantool) InsertSession(uid uint64, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSession", uid, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSession indicates an expected call of InsertSession.
func (mr *MockSessionTarantoolMockRecorder) InsertSession(uid, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSession", reflect.TypeOf((*MockSessionTarantool)(nil).InsertSession), uid, value)
}
